# Generated by Django 4.1.6 on 2023-06-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_srm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
