# Generated by Django 4.1.6 on 2023-06-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_srm', '0003_student_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
