# Generated by Django 4.1.6 on 2023-06-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_srm', '0004_income_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
