# Generated by Django 4.1.6 on 2023-06-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_srm', '0005_expense_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_srm.course', verbose_name='курс'),
        ),
    ]
