# Generated by Django 4.1.6 on 2023-06-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_srm', '0006_income_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_srm.employee', verbose_name='Ментор'),
        ),
        migrations.AlterField(
            model_name='income',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_srm.course', verbose_name='Kурс'),
        ),
    ]
